apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gin-hello-world-deployment
  labels:
    app: gin-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gin-hello-world
  template:
    metadata:
      labels:
        app: gin-hello-world
    spec:
      containers:
      - name: gin-hello-world
        image: karlhopkinsonturrell/gin-hello-world:2
        ports:
        - containerPort: 8080
#        livenessProbe:
#          httpGet:
#            path: /ping
#            port: 8080
#          periodSeconds: 1
#        readinessProbe:
#          httpGet:
#            path: /ping
#            port: 8080
#          periodSeconds: 1
#          initialDelaySeconds: 3
        env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: gin-hello-world-configmap
              key: app-message

